name: epic-cron
imageNamespace: c8b80a-tools
env: dev
environment: Development
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 200Mi
replicaCount: 1
imageTag: dev

cronTab: |
  0 1 * * * default cd /epic-cron && ./run_project_cron_submit.sh
  0 3 * * * default cd /epic-cron && ./run_project_cron_compliance.sh
  */6 * * * * default cd /epic-cron && ./run_emailer.sh
  */4 * * * * default cd /epic-cron && ./run_centre_emailer.sh
  10 * * * * default cd /epic-cron && ./run_approved_condition.sh

SUBMIT:
  database:
    host: submit-patroni.c72cba-dev.svc.cluster.local
    port: "5432"
  web:
    url: "https://dev.submit.eao.gov.bc.ca"
  sender:
    email: "EAO.ManagementPlanSupport.dev@gov.bc.ca"
  staffSupportMailId: "saravan.azhikoden@gov.bc.ca"
  signupUrlPath: "/proponent/registration"
  api:
    url: "https://submit-api-c72cba-dev.apps.gold.devops.gov.bc.ca"

COMPLIANCE:
  database:
    host: compliance-patroni
    port: "5432"

TRACK:
  database:
    host: epictrack-patroni
    port: "5432"
  api:
    url: "https://epictrack-api-c72cba-dev.apps.gold.devops.gov.bc.ca"

CENTRE:
  database:
    host: centre-patroni
    port: "5432"
  senderEmail: "EAO.EPICsystem.TEST@gov.bc.ca"
  pendingAccessReminder:
    hours: "48"
    email: "Don.Varghese@gov.bc.ca"
    baseUrl: "https://dev.submit.eao.gov.bc.ca"

CONDITION:
  api:
    url: "https://condition-api-c8b80a-dev.apps.gold.devops.gov.bc.ca"
  database:
    host: condition-patroni
    port: "5432"

SSL:
  notificationRecipients: "saravanpa@gmail.com,Saravan.Azhikoden@gov.bc.ca,Carly.GreeneHill@gov.bc.ca"

EPIC_PUBLIC:
  baseUrl: "https://projects.eao.gov.bc.ca"
  searchPath: "/api/public/search"
  documentTypeIds: "5cf00c03a266b7e1877504d1,5cf00c03a266b7e1877504d5,5df79dd77b5abbf7da6f51bf,5df79dd77b5abbf7da6f51cc"
  documentTypeMap: "5cf00c03a266b7e1877504d1:Other Order,5cf00c03a266b7e1877504d5:Certificate,5df79dd77b5abbf7da6f51bf:Other Order,5df79dd77b5abbf7da6f51cc:Certificate,5cf00c03a266b7e1877504d6:Exemption Order"
  maxPages: ""
  maxDocuments: ""
  enableDetailedLogs: "false"

KEYCLOAK:
  baseUrl: "https://dev.loginproxy.gov.bc.ca/auth"
  realmName: "eao-epic"

CHES:
  tokenEndpoint: "https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token"
  apiEndpoint: "https://ches-dev.api.gov.bc.ca"
  clientId: ""
  clientSecret: ""

CLAMAV:
  host: "142.34.194.68"
  port: "16504"

secrets:
  trackDbUsername: "app"
  trackDbPassword: ""
  trackDbName: "app"
  submitDbUsername: "app"
  submitDbPassword: ""
  submitDbName: "app"
  centreDbUsername: "app"
  centreDbPassword: ""
  centreDbName: "app"
  complianceDbUsername: "app"
  complianceDbPassword: "compliance_password_dev"
  complianceDbName: "app"
  conditionDbUsername: "app"
  conditionDbPassword: ""
  conditionDbName: "app"
  serviceAccountId: "submit-api-condition-client"
  serviceAccountSecret: ""
