apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    app: {{ .Values.name }}
    app-group: submit-app
data:
  crontab: |-
{{ .Values.cronTab | indent 4 }}
  # Database hosts and ports
  TRACK_DATABASE_HOST: "{{ .Values.TRACK.database.host }}"
  TRACK_DATABASE_PORT: "{{ .Values.TRACK.database.port }}"
  SUBMIT_DATABASE_HOST: "{{ .Values.SUBMIT.database.host }}"
  SUBMIT_DATABASE_PORT: "{{ .Values.SUBMIT.database.port }}"
  COMPLIANCE_DATABASE_HOST: "{{ .Values.COMPLIANCE.database.host }}"
  COMPLIANCE_DATABASE_PORT: "{{ .Values.COMPLIANCE.database.port }}"
  CENTRE_DATABASE_HOST: "{{ .Values.CENTRE.database.host }}"
  CENTRE_DATABASE_PORT: "{{ .Values.CENTRE.database.port }}"
  # CHES configuration
  CHES_TOKEN_ENDPOINT: "{{ .Values.CHES.tokenEndpoint }}"
  CHES_BASE_URL: "{{ .Values.CHES.apiEndpoint }}"
  # SUBMIT configuration
  WEB_URL: "{{ .Values.SUBMIT.web.url }}"
  SENDER_EMAIL: "{{ .Values.SUBMIT.sender.email }}"
  CENTRE_SENDER_EMAIL: "{{ .Values.CENTRE.senderEmail }}"
  STAFF_SUPPORT_MAIL_ID: "{{ .Values.SUBMIT.staffSupportMailId }}"
  SIGNUP_URL_PATH: "{{ .Values.SUBMIT.signupUrlPath }}"
  # Keycloak configuration
  KEYCLOAK_BASE_URL: "{{ .Values.KEYCLOAK.baseUrl }}"
  KEYCLOAK_REALM_NAME: "{{ .Values.KEYCLOAK.realmName }}"
  # Condition database host and port
  CONDITION_DATABASE_HOST: "{{ .Values.CONDITION.database.host }}"
  CONDITION_DATABASE_PORT: "{{ .Values.CONDITION.database.port }}"
  # API URLs
  CONDITION_API_BASE_URL: "{{ .Values.CONDITION.api.url }}"
  SUBMIT_API_BASE_URL: "{{ .Values.SUBMIT.api.url }}"
  SUBMIT_API_URL: "{{ .Values.SUBMIT.api.url }}"
  TRACK_API_BASE_URL: "{{ .Values.TRACK.api.url }}"
  # SSL checker notification recipients (comma-separated)
  SSL_NOTIFICATION_RECIPIENTS: "{{ .Values.SSL.notificationRecipients }}"
  # EPIC Public configuration
  EPIC_PUBLIC_BASE_URL: "{{ .Values.EPIC_PUBLIC.baseUrl }}"
  EPIC_PUBLIC_SEARCH_PATH: "{{ .Values.EPIC_PUBLIC.searchPath }}"
  EPIC_PUBLIC_DOCUMENT_TYPE_IDS: "{{ .Values.EPIC_PUBLIC.documentTypeIds }}"
  EPIC_PUBLIC_DOCUMENT_TYPE_MAP: "{{ .Values.EPIC_PUBLIC.documentTypeMap }}"
  EPIC_PUBLIC_MAX_PAGES: "{{ .Values.EPIC_PUBLIC.maxPages }}"
  EPIC_PUBLIC_MAX_DOCUMENTS: "{{ .Values.EPIC_PUBLIC.maxDocuments }}"
  ENABLE_DETAILED_LOGS: "{{ .Values.EPIC_PUBLIC.enableDetailedLogs }}"
  # ClamAV configuration
  CLAMAV_HOST: "{{ .Values.CLAMAV.host }}"
  CLAMAV_PORT: "{{ .Values.CLAMAV.port }}"
  # Other configuration
  CONNECT_TIMEOUT: "60"
  ENVIRONMENT: "{{ .Values.environment }}"
  # Pending Access Reminder configuration
  PENDING_ACCESS_REMINDER_HOURS: "{{ .Values.CENTRE.pendingAccessReminder.hours }}"
  PENDING_ACCESS_REMINDER_EMAIL: "{{ .Values.CENTRE.pendingAccessReminder.email }}"
  REQUEST_ACCESS_BASE_URL: "{{ .Values.CENTRE.pendingAccessReminder.baseUrl }}"
