apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app-group: epic-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app-group: epic-app
        environment: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: image-registry.openshift-image-registry.svc:5000/{{ .Values.imageNamespace }}/{{ .Values.name }}:{{ .Values.imageTag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: cron-config
              readOnly: true
              mountPath: /epic-cron/cron/
          env:
            - name: TRACK_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: TRACK_DATABASE_USERNAME
            - name: TRACK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: TRACK_DATABASE_PASSWORD
            - name: TRACK_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: TRACK_DATABASE_NAME
            - name: TRACK_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: TRACK_DATABASE_HOST
            - name: TRACK_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: TRACK_DATABASE_PORT

            - name: SUBMIT_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: SUBMIT_DATABASE_USERNAME
            - name: SUBMIT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: SUBMIT_DATABASE_PASSWORD
            - name: SUBMIT_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: SUBMIT_DATABASE_NAME
            - name: SUBMIT_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SUBMIT_DATABASE_HOST
            - name: SUBMIT_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SUBMIT_DATABASE_PORT

            - name: COMPLIANCE_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: COMPLIANCE_DATABASE_USERNAME
            - name: COMPLIANCE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: COMPLIANCE_DATABASE_PASSWORD
            - name: COMPLIANCE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: COMPLIANCE_DATABASE_NAME
            - name: COMPLIANCE_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: COMPLIANCE_DATABASE_HOST
            - name: COMPLIANCE_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: COMPLIANCE_DATABASE_PORT

            - name: CENTRE_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CENTRE_DATABASE_USERNAME
            - name: CENTRE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CENTRE_DATABASE_PASSWORD
            - name: CENTRE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CENTRE_DATABASE_NAME
            - name: CENTRE_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CENTRE_DATABASE_HOST
            - name: CENTRE_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CENTRE_DATABASE_PORT

            - name: CHES_TOKEN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CHES_TOKEN_ENDPOINT
            - name: CHES_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CHES_BASE_URL
            - name: CHES_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CHES_CLIENT_ID
            - name: CHES_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CHES_CLIENT_SECRET

            - name: WEB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: WEB_URL
            - name: SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SENDER_EMAIL
            - name: CENTRE_SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CENTRE_SENDER_EMAIL
            - name: STAFF_SUPPORT_MAIL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: STAFF_SUPPORT_MAIL_ID
            - name: SIGNUP_URL_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SIGNUP_URL_PATH

            - name: KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: KEYCLOAK_BASE_URL
            - name: KEYCLOAK_REALM_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: KEYCLOAK_REALM_NAME
            - name: SERVICE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: SERVICE_ACCOUNT_ID
            - name: SERVICE_ACCOUNT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: SERVICE_ACCOUNT_SECRET
            - name: CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CONNECT_TIMEOUT

            - name: CONDITION_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CONDITION_DATABASE_USERNAME
            - name: CONDITION_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CONDITION_DATABASE_PASSWORD
            - name: CONDITION_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: CONDITION_DATABASE_NAME
            - name: CONDITION_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CONDITION_DATABASE_HOST
            - name: CONDITION_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CONDITION_DATABASE_PORT

            - name: CONDITION_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CONDITION_API_BASE_URL

            - name: SUBMIT_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SUBMIT_API_BASE_URL
            - name: SUBMIT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SUBMIT_API_URL

            - name: TRACK_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: TRACK_API_BASE_URL

            - name: SSL_NOTIFICATION_RECIPIENTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: SSL_NOTIFICATION_RECIPIENTS

            - name: EPIC_PUBLIC_DOCUMENT_TYPE_IDS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: EPIC_PUBLIC_DOCUMENT_TYPE_IDS

            - name: EPIC_PUBLIC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: EPIC_PUBLIC_BASE_URL
            - name: EPIC_PUBLIC_SEARCH_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: EPIC_PUBLIC_SEARCH_PATH
            - name: EPIC_PUBLIC_DOCUMENT_TYPE_MAP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: EPIC_PUBLIC_DOCUMENT_TYPE_MAP
            - name: EPIC_PUBLIC_MAX_PAGES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: EPIC_PUBLIC_MAX_PAGES
            - name: EPIC_PUBLIC_MAX_DOCUMENTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: EPIC_PUBLIC_MAX_DOCUMENTS
            - name: ENABLE_DETAILED_LOGS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: ENABLE_DETAILED_LOGS

            - name: CLAMAV_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CLAMAV_HOST
            - name: CLAMAV_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: CLAMAV_PORT

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: ENVIRONMENT

            - name: PENDING_ACCESS_REMINDER_HOURS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: PENDING_ACCESS_REMINDER_HOURS
            - name: PENDING_ACCESS_REMINDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: PENDING_ACCESS_REMINDER_EMAIL
            - name: REQUEST_ACCESS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: REQUEST_ACCESS_BASE_URL

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: cron-config
          configMap:
            name: {{ .Values.name }}-config
            defaultMode: 420
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
